name: learning_image_labeling
description: The easy way to use ML Kit for image labeling in Flutter.
version: 0.0.2
# author: Salman S
homepage: https://github.com/salkuadrat/learning/tree/master/packages/learning_image_labeling
repository: https://github.com/salkuadrat/learning/tree/master/packages/learning_image_labeling

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  learning_input_image: ^0.0.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.salkuadrat.learning.learning_image_labeling
        pluginClass: LearningImageLabelingPlugin
      ios:
        pluginClass: LearningImageLabelingPlugin
