name: learning_digital_ink_recognition
description: The easy way to use ML Kit for digital ink recognition in Flutter.
version: 0.0.2
# author: Salman S
homepage: https://github.com/salkuadrat/learning/tree/master/packages/learning_digital_ink_recognition
repository: https://github.com/salkuadrat/learning/tree/master/packages/learning_digital_ink_recognition

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.salkuadrat.learning.learning_digital_ink_recognition
        pluginClass: LearningDigitalInkRecognitionPlugin
      ios:
        pluginClass: LearningDigitalInkRecognitionPlugin
