name: learning_barcode_scanning
description: The easy way to use ML Kit for barcode scanning in Flutter.
version: 0.0.3
# author: Salman S
homepage: https://github.com/salkuadrat/learning/tree/master/packages/learning_barcode_scanning
repository: https://github.com/salkuadrat/learning/tree/master/packages/learning_barcode_scanning

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  learning_input_image: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.salkuadrat.learning.learning_barcode_scanning
        pluginClass: LearningBarcodeScanningPlugin
      ios:
        pluginClass: LearningBarcodeScanningPlugin
