name: learning_language
description: The easy way to use ML Kit for identifying languages in Flutter.
version: 0.0.4
# author: Salman S
homepage: https://github.com/salkuadrat/learning/tree/master/packages/learning_language
repository: https://github.com/salkuadrat/learning/tree/master/packages/learning_language

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.salkuadrat.learning.learning_language
        pluginClass: LearningLanguagePlugin
      ios:
        pluginClass: LearningLanguagePlugin