name: learning_smart_reply
description: The easy way to use ML Kit for generating smart replies in Flutter.
version: 0.0.3
# author: Salman S
homepage: https://github.com/salkuadrat/learning/tree/master/packages/learning_smart_reply
repository: https://github.com/salkuadrat/learning/tree/master/packages/learning_smart_reply

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.salkuadrat.learning.learning_smart_reply
        pluginClass: LearningSmartReplyPlugin
      ios:
        pluginClass: LearningSmartReplyPlugin
