name: learning_input_image
description: Input image package to be used by other learning plugins.
version: 0.0.6+2
# author: Salman S
homepage: https://github.com/salkuadrat/learning/tree/master/packages/learning_input_image

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  image_picker: ^0.8.4+4
  camera: ^0.9.4+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/flip_camera.svg
    - assets/gallery.svg
    - assets/camera.svg
    - assets/image.svg
