name: learning_smart_reply_example
description: Demonstrates how to use the learning_smart_reply plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.5
  learning_smart_reply: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
